[theme]
font = "Kanit:https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;500;600;700&display=swap"
headingFont = "Kanit:https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;500;600;700&display=swap"
